- name: Login with ibmcloud Cli
  shell:
    cmd: ibmcloud login --apikey "{{ API_KEY }}" -r "{{ REGION }}" -g "{{ RESOURCE_GROUP }}"

- name: Select Code Engine Project
  shell: 
    cmd: ibmcloud ce project select -n "{{ PROJECT }}"

- name: Update Code Engine application variable
  shell:
    cmd: ibmcloud ce application update -n "{{ APPLICATION }}" --env "{{ ENV_KEY }}"="{{ ENV_VALUE }}"
